{% set name = "wxdata" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wxdata-{{ version }}.tar.gz
  sha256: 39f6ddff060aca9ec470086be7e2e5032038051b1bd67e1461aa710f490d16e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - metpy >=1.7.1
    - numpy >=2.2.6
    - pandas >=2.3.3
    - cartopy >=0.25.0
    - xarray >=2025.6.1
    - netcdf4 >=1.7.3
    - shapeography >=1.2
    - beautifulsoup4 >=4.14.3
    - requests >=2.32.5
    - cfgrib >=0.9.15.1
    - dask-core >=2025.11.0
    - tqdm >=4.67.3
    - ecmwf-opendata >=0.3.26
    - openpyxl >=3.1.5
    - arm_pyart >=2.2.0

test:
  imports:
    - wxdata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edrewitz/WxData
  summary: A Python package of end-to-end weather data clients & raw data clients with VPN/Proxy Server support, data processors that decode variable keys from GRIB format into a plain-language format & various tools for assisting Python automated workflows, querying meteorological datasets and filling gaps in meteorological data.
  license: MIT
  license_file: LICENSE
  doc_url: https://pypi.org/project/wxdata/
  dev_url: https://github.com/edrewitz/WxData
  description: |

    Project Description
    -------------------
    WxData is a Python package geared to help atmospheric scientists set up automated workflows that download,
    pre-process and post-process various types of weather data (observational and forecast).

    Data Clients
    ------------
    There are two classes of clients: End-To-End and Raw. End-To-End clients download, pre-process and post process data 
    specific to a type of dataset (i.e. gfs0p25() for GFS (0.25x0.25) Data). Raw clients assist users in downloading different
    types of data (i.e. get_gridded_data(), get_csv_data(), get_excel_data(), get_aws_open_data() and get_xmacis_data()).
    These clients have built-in support for users working on VPN/PROXY connections. Users will need to define their own
    PROXY settings and pass those settings into the client so the client knows the path from the HOST to the Data Server. 

    Post-Processors
    ---------------
    WxData has post-processing modules for every type of dataset that has an end-to-end client. Users may also import these
    post-processing modules if they wish to use their own downloading procedures. 

    Data Querying Tools
    -------------------
    WxData has tools to assist users with pixel and line querying for gridded datasets. 

    Data Transformation & Gap Filling Tools
    ---------------------------------------
    WxData has tools to assist users with:

    1) Shifting longitude in gridded datasets from a 0 to 360 into a -180 to 180 projection.
    2) Adding cyclic points to resolve data gaps along the 180 or 0 degree meridian in gridded datasets.
    3) Linearly interpolating between two data points.

    Automated Python Workflow Tools
    -------------------------------
    WxData has a tool users can use to execute a series of Python scripts in the order the user lists them in. 

extra:
  recipe-maintainers:
    - edrewitz
